language: java

sudo: false

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=4 CC=clang CXX=clang++

before_install:
  - nvm install $NODE_VERSION

before_script:
  - npm install -g bower

script: mvn clean install